### PR TITLE
make EGL backend work

### PR DESCRIPTION
**Pull request by wangg12**
@MartinSmeyer This might solve the problem of rendering on a remote server.

reference:
[https://github.com/mmatl/pyrender/blob/master/pyrender/offscreen.py](https://github.com/mmatl/pyrender/blob/master/pyrender/offscreen.py)

### CODE REVIEW

**Comment by MartinSmeyer** [comment]
Hey Wang,
thanks a lot for your PR. I was just about to inspect it, sorry for the delay. It does support offscreen CPU-based rendering with OS Mesa correct? 
Why did you close it?

**Comment by wangg12** [comment]
I thought that you might not want it.
I don't know whether it is cpu or gpu based. It should be gpu-based since it uses egl which is a shared library of nvidia opengl driver.

**Comment by MartinSmeyer** [comment]
No, I would be happy to test it. Thanks for making the effort I was on vacation before..

**Comment by MartinSmeyer** [comment]
Could you reopen it?

**Comment by wangg12** [comment]
I will open another one since I made an wrong commit in this PR.

**Comment by MartinSmeyer** [comment]
okay great :)

**Comment by MartinSmeyer** [comment]
I will check it tomorrow morning, then!

**Pull request closed without merging**
